#!/usr/bin/env scons

import os

from os.path import join
from nestly.scons import SConsWrap
from nestly import Nest
import SCons.Script as sc

# Command line options

sc.AddOption('--output', type='string', help="output folder", default='_output')
sc.AddOption('--cluster', type='string', help="use cluster?", default='local')

env = sc.Environment(
        ENV=os.environ,
        output=sc.GetOption('output'),
        cluster=sc.GetOption('cluster'),
        )

sc.Export('env')

env.SConsignFile()

flags = [
        # 'simulation',
        # 'simulation_comparators',
        # 'simulation_agg',
        'casestudy',
        # 'modelfix',
]

for flag in flags:
        sc.SConscript(flag + '/sconscript', exports=['flag'])
